name: "TheActionDev"
description: "dev.to Posts with GitHub Action 🧑‍💻"
author: "Kaiz Khatri"

inputs:
  apiKey:
    description: "Api Key from dev.to"
    required: true
  articelsPath:
    description: "Airticels will sync with dev.to"
    default: "."
  ignoreFiles:
    description: "Files are ignored in dev.to Sync. Multiple files are separated by ','(Comma)."

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "code"
  color: "gray-dark"
