name: "TheActionDev"
description: "dev.to Posts with GitHub Action 🧑‍💻"
author: "Kaiz Khatri"

inputs:
  token:
    required: true
    description: "Token from dev.to"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "code"
  color: "gray-dark"
