name: "TheActionDev"
description: "Write dev.to articles with GitHub Action"
author: "Kaiz Khatri"

inputs:
  api-key:
    description: "Api Key from dev.to"
    required: true
  directory:
    description: "Path to 'dev.to' articles"
    default: "."
  ignore:
    description: "Files are ignored by action. Multiple files are separated by ','(Comma)."

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "code"
  color: "gray-dark"
