name: "test-run"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
      - "releases/*"

jobs:
  test-run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          api-key: ${{ secrets.DEVTO_API_KEY }}
          directory: ./docs
          ignore: DEVELOPMENT.md
