name: "build-test"
on: # rebuild any PRs and main branch changes
  schedule:
    - workflow_dispatch
  pull_request:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run action
  test-run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          api-key: ${{ secrets.DEV_TO_TOKEN }}
          directory: ./docs
          ignore: contributors.md
